[project]
name = "jupyter-content"
version = "0.1.0"
description = "Environment for Comp Tools Res Jupyter and Marimo notebooks"
readme = "README.md"
authors = [
    { name = "Matt Gitzendanner", email = "magitz@ufl.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4",
    "matplotlib",
    "marimo",
    "numpy",
    "openpyxl",
    "pandas",
    "pillow",
    "requests",
    "scipy",
    "seaborn",
    "scikit-learn",
    "sqlalchemy",
    "tensorflow",
    "xgboost",
]

[project.scripts]
jupyter-content = "jupyter_content:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
